name: Bluecard check
run-name: Bluecard check case 🚀
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  BuildAndRunRobot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare workspace for artifacts
        run: |
          mkdir ${{ github.workspace }}/test/
          ARTIFACTS_SHA=$(git rev-parse --short HEAD)
          echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Robot test case
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          image: robot:main
          options: |
            -v ${{ github.workspace }}:/workspace -e USER_UID=1001
          shell: bash
          run: |
            robot /workspace/test/OkpWizard.robot
            cp -r /opt/results/* /workspace/test/
            cp -r /opt/screenshots/* /workspace/test/
            
      - uses: actions/upload-artifact@v4
        with:
          name: robot-artifacts-${{ env.ARTIFACTS_SHA }}
          retention-days: 1
          path: |
            ${{ github.workspace }}/test/*
