name: Bluecard check
run-name: Bluecard check case 🚀

on:
  schedule:
    - cron: "29 04 * * *"
  workflow_dispatch:
  # push:
  #   paths:
  #   - '.github/**'
  #   - 'tests/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  ROBOT_OPTIONS: "--outputdir results --suitestatlevel 2"
  PYTHONPATH: "/opt/pkg/"

jobs:
  check-card:
    runs-on: ubuntu-latest
    name: check-card
    environment:
      name: my
    permissions:
      contents: read
    container: 
      image: ghcr.io/shearwater1978/robot:main
    steps:
      - uses: actions/checkout@v3

      - name: Add path
        run: |
          echo "/opt/pkg/bin/" >> $GITHUB_PATH

      - name: downcase REPO
        run: |
          echo "MYDATA=${MYDATA}" >> ${GITHUB_ENV}
          echo "NOW=$(date +'%d-%m-%Y %H:%M')" >> $GITHUB_ENV
        env:
          MYDATA: ${{ secrets.MYDATA64 }}

      - name: Run Robot test case
        run: |
          echo ${{ env.MYDATA }} | base64 -d > tests/mydata.json
          res=$(robot tests/malopolska.robot | grep 'Rezerwacja Validate results' | cut -d '|' -f2 | sed 's| ||g')
          echo "res=${res}" >> ${GITHUB_ENV}

      - name: Send Telegram Message Ok
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Date: "${{ env.NOW }}"
            Card issue status: "${{ env.res }}"
