name: Bluecard check
run-name: Bluecard check case 🚀
on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  RunRobot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare workspace for artifacts
        run: |
          mkdir -p ${{ github.workspace }}/tests/
          ARTIFACTS_SHA=$(git rev-parse --short HEAD)
          echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: downcase REPO
        run: |
          echo "REPO=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "/workspace/tests/mydata.json"
          json: ${{ secrets.MYDATA }}
          
      - name: Run Robot test case
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.REGISTRY }}/${{ env.REPO }}:main
          options: |
            -v ${{ github.workspace }}:/workspace -e USER_UID=1001
          shell: bash
          run: |
            pwd
            ls -la
            robot /workspace/tests/malopolska.robot
            cp -r /opt/results/* /workspace/tests/ || true
            cp -r /opt/screenshots/* /workspace/tests/ || true
            ls -la
            
      - uses: actions/upload-artifact@v4
        with:
          name: robot-artifacts-${{ env.ARTIFACTS_SHA }}
          retention-days: 1
          path: |
            ${{ github.workspace }}/tests/*
