name: Bluecard check
run-name: Bluecard check case 🚀

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/**'
    - 'tests/**'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  RunRobot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: my
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare workspace for artifacts
        run: |
          mkdir -p ${{ github.workspace }}/tests/ ${{ github.workspace }}/results/
          ARTIFACTS_SHA=$(git rev-parse --short HEAD)
          echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO
        run: |
          echo "REPO=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
          echo "MYDATA=${MYDATA}" >> ${GITHUB_ENV}
        env:
          MYDATA: ${{ secrets.MYDATA64 }}

      - name: Run Robot test case
        uses: addnab/docker-run-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.REGISTRY }}/${{ env.REPO }}:main
          options: |
            -v ${{ github.workspace }}:/workspace -e USER_UID=1001
          shell: bash
          run: |
            echo ${{ env.MYDATA }} | base64 -d > /workspace/tests/mydata.json
            result=$(robot /workspace/tests/malopolska.robot | grep 'Rezerwacja Validate results' | cut -d '|' -f2 | sed 's| ||g')
            # robot -x /workspace/results/outputxunit.xml /workspace/tests/malopolska.robot
            echo "Rezerwacja Validate results=${result}" >> $GITHUB_OUTPUT
            echo "Rezerwacja Validate results=${result}" >> $GITHUB_STEP_SUMMARY
            # cp -r /opt/results/* /workspace/results/ || true
            # cp -r /opt/screenshots/* /workspace/results/ || true
            
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: robot-artifacts-${{ env.ARTIFACTS_SHA }}
      #     retention-days: 1
      #     path: |
      #       ${{ github.workspace }}/results/*
