name: Robot execute
run-name: Run Robot test case 🚀
on:
  workflow_dispatch:
jobs:
  BuildAndRunRobot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          tags: robot:latest
          load: true
      - name: Run Robot test case
        uses: addnab/docker-run-action@v3
        with:
          image: robot:latest
          options: 
            -v ${{ github.workspace }}/artifacts/results/:/opt/results/* -v ${{ github.workspace }}/artifacts/screenshots/:/opt/screenshots/* -v ${{ github.workspace }}:/workspace -v ${{ github.workspace }}/tests/:/opt/tests/
          run: |
            robot tests/youtube.robot
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifacts
          path: |
            ${{ github.workspace }}/artifacts/results/*
            ${{ github.workspace }}/artifacts/screenshots/*
