name: Robot execute
run-name: Run Robot test case 🚀
on:
  workflow_dispatch:
jobs:
  BuildAndRunRobot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare workspace for artifacts
        run: |
          mkdir ${{ github.workspace }}/test/
          ARTIFACTS_SHA=$(git rev-parse --short HEAD)
          echo "ARTIFACTS_SHA=$ARTIFACTS_SHA" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          tags: robot:latest
          load: true
          build-args: USER_UID=1001
          
      - name: Run Robot test case
        uses: addnab/docker-run-action@v3
        with:
          image: robot:latest
          options: |
            -v ${{ github.workspace }}:/workspace -e USER_UID=1001
          run: |
            id
            pip freeze
            whereis robot || true
            robot /workspace/tests/youtube.robot || true
            cp -r /opt/results/* /workspace/test/|| true
            cp -r /opt/screenshots/* /workspace/test/ || true
            
      - uses: actions/upload-artifact@v4
        with:
          name: robot-artifacts-${{ env.ARTIFACTS_SHA }}
          retention-days: 1
          path: |
            ${{ github.workspace }}/test/*
