name: Robot
run-name: Robot

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ROBOT_OPTIONS: "--outputdir results --suitestatlevel 2"
  PYTHONPATH: "/opt/pkg/"

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: my
    permissions:
      contents: read
    container: 
      image: ghcr.io/shearwater1978/robot:main
    steps:
      - uses: actions/checkout@v3
      - name: Add path
        run: |
          echo "/opt/pkg/bin/" >> $GITHUB_PATH
      - name: Running inside Container
        run: pip list -v
