name: Robot
run-name: Robot

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ROBOT_OPTIONS: "--outputdir results --suitestatlevel 2"

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: my
    permissions:
      contents: read
    container: 
      image: ghcr.io/myrepo/robot:main
      options: --user 1001
    steps:
      - name: Running inside Container
        run: |
          echo "Running inside Container"
          env
          echo $PATH
          pip list
          robot --version
