name: Robot
run-name: Robot

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ROBOT_OPTIONS: "--outputdir results --suitestatlevel 2"
  PYTHONPATH: "/opt/pkg/"

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: my
    permissions:
      contents: read
    container: 
      image: ghcr.io/shearwater1978/robot:main
    steps:
      - uses: actions/checkout@v3
      - name: Add path
        run: |
          echo "/opt/pkg/bin/" >> $GITHUB_PATH
      - name: Running inside Container
        run: robot --help
        
  send:
    runs-on: ubuntu-latest
    environment:
      name: my
    permissions:
      contents: read
    steps:
      - name: Send Telegram Message Ok
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *1st line of your message with bold*
            *2nd line of your message with bold, too*
            Application: *Write something to be put inside your message*. The below lines still are part of your message.          
            Branch: *${{ github.ref }}*
            Repository: *${{ github.repository }}*
            Owner: *${{ github.repository_owner }}*
