name: Robot
run-name: Robot

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ROBOT_OPTIONS: "--outputdir results --suitestatlevel 2"

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: my
    permissions:
      contents: read
    container: 
      image: ghcr.io/shearwater1978/robot:main
    steps:
      - uses: actions/checkout@v3
      - name: Running inside Container
        run: |
          echo "Running inside Container"
          env
          echo $PATH
          python -c "import robot" || true
          python -c "import robot123" || true
          ls -la /home/robot/.local/lib/python3.11/site-packages/robot/ || true
          which robot
